import 'idempotent-babel-polyfill'
import svg4everybody from 'svg4everybody'
// import 'simplebar'
import './modules/header'
import './modules/sliders'
import './modules/scroll-to-anchor'
import './modules/dropdowns'
import './modules/people-modal'
import './modules/news'
import './modules/cookies'
import './modules/list-load-more'
import './modules/accordions'
import './modules/map/map'
import './modules/video-lazy-loading'

svg4everybody()
